version: "3"
services:
  dbservice:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ppmtcourse
      MYSQL_USER: theuser
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./db-data:/var/lib/mysql
  be:
    image: yosua161/ppm-be:latest      
    depends_on:
      - dbservice
    ports:
      - "8081:8081"