version: "3"
services:
  dbservice:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ppmtcourse
      MYSQL_USER: theuser
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      DATABASE_PORT: "3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - backend
  be:
    image: yosua161/ppm-be:latest      
    depends_on:
      - dbservice
    ports:
      - "8081:8081"
    networks:
      - backend
      - frontend
  fe:
    image: yosua161/ppm-fe:latest
    depends_on:
      - be
    ports:
      - "3000:80"
    networks:
      - frontend
    build:
      context: polling-app-client # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://13.229.71.53:8081/

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: