version: "3"
services:
  dbservice:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ppmtcourse
      MYSQL_USER: theuser
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      DATABASE_PORT: "3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - backend
  be:
    image: yosua161/ppm-be:latest      
    depends_on:
      - dbservice
    ports:
      - "8081:8081"
    networks:
      - backend
      - frontend
  fe:
    image: yosua161/ppm-fe:latest
    depends_on:
      - be
    ports:
      - "443:443"
      - "90:80"
    networks:
      - frontend
    volumes:
      - /html:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
  certbot:
    image: certbot/certbot
    depends_on:
      - fe
    volumes:
      - /html:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email yosua161@gmail.com --agree-tos --no-eff-email --force-renewal -d yossi.pw -d www.yossi.pw 
  
# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
volumes:
  web-root:
  certbot-etc:
  certbot-var: